#!/usr/bin/env python3
"""
.. module:: runltp-ng
    :platform: Linux
    :synopsis: Entry point of the runltp-ng tool.
.. moduleauthor:: Andrea Cervesato <andrea.cervesato@suse.com>
"""

# pylint: disable=invalid-name

import os
import sys

# include ltp library
sys.path.insert(0, os.path.abspath(os.path.dirname(__file__)))
sys.path.insert(0, os.path.abspath(os.path.join(
    os.path.dirname(__file__),
    "runltp-ng.d")
))

if __name__ == "__main__":
    import ltp.main
    ltp.main.run()
